[package]
name = "austral"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
austral_lib = { path = "../../lib/austral_lib" }
chumsky = "1.0.0-alpha.6"
clap = {version = "4.4.11", features = ["derive"]}
melior = { version = "0.15.0" }
